services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hekolearnDB
    ports:
      - 5432:5432
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
